name: Deploy Data to Staging

on:
  # Launches when manually triggered with the new workflow_dispatch event
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # Script to deploy to staging environment
      - name: 'Deploy to S3: Staging'
        if: github.ref == 'refs/heads/main'
        run: |
          cd ${{ github.workspace }}
          aws s3 sync . s3://${{ secrets.AWS_STAGING_BUCKET_NAME }}/current \
          --exclude='*' \
          --include='data.json' \
          --include='logos/*' \
          --include='index.html'
        working-directory: ${{ github.workspace }}